### ISSUE TITLE
ft_simpleimagewrite fails 

### ISSUE THREAD

**Issue by bamcleod** [ericmandel/funtools#19]
ft_simpleimagewrite  fails with ERROR: illegal memory buffer specification
The problem appears to be that the 'b' in the 'wb' file mode makes the Open call think that it is trying to open a memory buffer.  Changing 'wb' to 'w' solves the problem.  Not sure if there are other implications.

**Comment by ericmandel** [comment]
@bamcleod Funtools is unsupported  since 2007 but ... what OS are you using? From xos.h, it looks to me like ftOpen() is really fopen() and the Centos8 (and macOS) man page for fopen() contains this:
````
      The mode string can also include the letter 'b' either as a last  char‐
       acter  or as a character between the characters in any of the two-char‐
       acter strings described above.  This is strictly for compatibility with
       C89  and has no effect; the 'b' is ignored on all POSIX conforming sys‐
       tems, including Linux.  (Other systems may treat text files and  binary
       files  differently, and adding the 'b' may be a good idea if you do I/O
       to a binary file and expect that your program may be ported to non-UNIX
       environments.)
````
So ... it should work in the usual case, right? Are you on a system where the 'b' means something different in fopen()??

I certainly can remove the 'b' since it really shouldn't do anything, but it would be good to understand what your fopen() man page says ...

**Comment by bamcleod** [comment]
I'm doing this on CentOS7 (CF-managed workstation)

When I run the debugger I get to util/gio.c line 1200 where it looks for a
'b' in the mode string and thus decides it is a memory block rather than an
ordinary file.

When I build funtools, fitsy is getting compiled with -DUSE_XFILEIO=1 which
I think sends me down the gopen trail, rather than fopen.

**Comment by ericmandel** [comment]
Ah, yes, I see now, gio does use 'b' for buffer (probably shouldn't but ...) Since 'b' should be ignored on all reasonable OSes when calling fopen() and since gopen() uses it differently, I've removed it from this call and updated the repository.

That said, please do remember that this is unsupported software ... I recommend you find something else!

**Comment by bamcleod** [comment]
Thanks, Eric.  I was trying to do a 64-bit compilation of some code that I
last compiled 10 years ago. Unsupported code calling other unsupported code!
